### PR TITLE
Release version 1.0.3

### LINKED ISSUE #9670: [BOOM-5316] Brand list module
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-5316).

- _**Reporter:**_ marion_francois
- _**Created at:**_ Fri, 13 Apr 2018 16:55:55 +0200

<p>In brand list module, I can choose to display brands in plain text or drop-down.</p>

<p>If I choose drop-down, it's not very pretty</p>
        
capture du 2018-04-13 16-54-35

### LINKED ISSUE #18463: FO - `ps_brandlist` module - The title link for the Brands is not working when "Display brands" is enabled
#### Describe the bug

When the `ps_brandlist` module is installed and the option "Display brands" is enabled, in the FO => Categories page => the title link for the Brands is not working.
It is working only when the "Display suppliers" option is enabled **and** "Display brands" is enabled.
PR related: https://github.com/PrestaShop/PrestaShop/pull/14665

#### Expected behavior

The title should be working independently from the supplier's option.

#### Steps to Reproduce

1. Install `ps_brandlist` module
2. Try to configure your smarty by disabling the cache set the option "Template compilation" to Force compilation and clear cache.
2. Go to BO => Shop Parameters => General page => Enable "Display brands" and disable "Display suppliers" option
3. Clear cache
3. Go to the FO => Categories page
4. Try to click on the **BRANDS** title => it is not working

If you the "Display suppliers" option => it will be OK.

**Screenshots**
image
https://drive.google.com/file/d/1I6jL2RM6F8oLRgEslhXmi2UOVOmd99h8/view?usp=sharing
#### Additional information

* PrestaShop version: 1.7.7.x, develop
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Release version 1.0.3
| How to test? | See below

### How to test?

List of the changes since version 1.0.2
- https://github.com/PrestaShop/ps_brandlist/pull/6 fixes https://github.com/PrestaShop/PrestaShop/issues/9670
- https://github.com/PrestaShop/ps_brandlist/pull/8 fixes https://github.com/PrestaShop/PrestaShop/issues/18463

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by florine2623** [comment]
Hello @matks ,

I cant' find the module in PS 1.7.8.x :
Screenshot 2022-01-10 at 18 09 33

I've checked the files, the `ps_brandlist` folder is present in `my_shop/modules`

On branch develop, it is OK.

Could you check ?
Thanks!

**Comment by atomiix** [comment]
@florine2623 I think you should install it from the module catalog:
Capture d’écran 2022-01-13 à 17 57 33

**Comment by PierreRambaud** [comment]
> Hello @matks ,
> 
> I cant' find the module in PS 1.7.8.x : Screenshot 2022-01-10 at 18 09 33
> 
> I've checked the files, the `ps_brandlist` folder is present in `my_shop/modules`
> 
> On branch develop, it is OK.
> 
> Could you check ? Thanks!

I confirme what @atomiix said, the behavior between 1.7.8.x and develop is not the same ot install a module :wink:

**Comment by florine2623** [comment]
Hello all,

Thanks for the update !
It looks good to me ✅

**Comment by Progi1984** [comment]
Thanks @matks & @florine2623

**Pull request merged**
